spring:
  datasource:
    name: database
    url: jdbc:postgresql://localhost:5432/ecf
    username: postgres
    password: root
  jpa:

    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
        hbm2ddl:
          auto: create-drop

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql:
              BasicBinder: TRACE
server:
  port: 8080
